version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4
  mruby: baldowl/mruby@dev:alpha

workflows:
  dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: baldowl/mruby
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-workflow:
          ssh-fingerprints: 48:b5:bb:87:2c:32:db:38:da:71:c0:3d:3d:30:dc:17
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master
  int:
    jobs:
      - mruby/test:
          build_config_file: mruby/build_config.rb
          version: "master"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /integration-.*/
