version: 2.1

parameters:
  dev-orb-version:
    type: string
    default: dev:alpha
  run-integration-tests:
    type: boolean
    default: false

orbs:
  orb-tools: circleci/orb-tools@9.1.0
  mruby: baldowl/mruby@<< pipeline.parameters.dev-orb-version >>

workflows:
  check-and-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: baldowl/mruby
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          requires:
            - orb-tools/publish-dev
  test-and-publish:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - mruby/test:
          build_command: rake
          build_config_file: mruby/build_config/default.rb
          mri_image: ruby:3.0.0-slim
          system_dependencies:
            - run: apt-get update -qq
            - run: apt-get install -y -qq gcc git
          version: master
      - orb-tools/dev-promote-prod-from-commit-subject:
          add-pr-comment: false
          fail-if-semver-not-indicated: false
          orb-name: baldowl/mruby
          publish-version-tag: true
          ssh-fingerprints: 48:b5:bb:87:2c:32:db:38:da:71:c0:3d:3d:30:dc:17
          requires:
            - mruby/test
          filters:
            branches:
              only: master
  refresh-dev-version:
    triggers:
      - schedule:
          cron: "0 5 1 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: baldowl/mruby
          publish-sha-version: false
          requires:
            - orb-tools/pack
